
CREATE TABLE "T_DEPARTMENT"(
  "ID" INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(128) NOT NULL,
  "LOCATION" VARCHAR(128) NOT NULL,
  "MIXEDCASE" VARCHAR(128)
);

CREATE TABLE "T_EMPLOYEE"(
  "ID" INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(128) NOT NULL,
  "JOB" VARCHAR(128) NOT NULL,
  "MANAGER_ID" INT NULL,
  "HIRE_DATE" DATE NOT NULL,
  "SALARY" BIGINT NOT NULL,
  "DEPARTMENT_ID" INT NOT NULL
);

CREATE SCHEMA "COMPANY";
CREATE TABLE "COMPANY"."T_CUSTOMER" (
  "ID" INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(128) NOT NULL,
  "EMAIL" VARCHAR(128) NOT NULL,
  "PHONE_NUMBER" VARCHAR(128) NOT NULL
);

INSERT INTO "T_DEPARTMENT"("NAME", "LOCATION") VALUES ('TECH', 'GUANGZHOU');
INSERT INTO "T_DEPARTMENT"("NAME", "LOCATION") VALUES ('FINANCE', 'BEIJING');

INSERT INTO "T_EMPLOYEE"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('VINCE', 'ENGINEER', NULL, '2018-01-01', 100, 1);
INSERT INTO "T_EMPLOYEE"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('MARRY', 'TRAINEE', 1, '2019-01-01', 50, 1);

INSERT INTO "T_EMPLOYEE"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('TOM', 'DIRECTOR', NULL, '2018-01-01', 200, 2);
INSERT INTO "T_EMPLOYEE"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('PENNY', 'ASSISTANT', 3, '2019-01-01', 100, 2);



CREATE TABLE "T_EMPLOYEE0"(
  "ID" INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(128) NOT NULL,
  "JOB" VARCHAR(128) NOT NULL,
  "MANAGER_ID" INT NULL,
  "HIRE_DATE" DATE NOT NULL,
  "SALARY" BIGINT NOT NULL,
  "DEPARTMENT_ID" INT NOT NULL
);

INSERT INTO "T_EMPLOYEE0"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('VINCE', 'ENGINEER', NULL, '2018-01-01', 100, 1);
INSERT INTO "T_EMPLOYEE0"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('MARRY', 'TRAINEE', 1, '2019-01-01', 50, 1);

INSERT INTO "T_EMPLOYEE0"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('TOM', 'DIRECTOR', NULL, '2018-01-01', 200, 2);
INSERT INTO "T_EMPLOYEE0"("NAME", "JOB", "MANAGER_ID", "HIRE_DATE", "SALARY", "DEPARTMENT_ID")
    VALUES ('PENNY', 'ASSISTANT', 3, '2019-01-01', 100, 2);